version: '3.3'

services:
  web:
    build: .
    container_name: webapp
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/geographical-distance-calculator
    ports:
      - "8000:8000"
    depends_on:
      - db  
  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=johndoepass
      - POSTGRES_DB=geodistancecalculator
    ports:
      - "5435:5432"